name: docmind
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: docmind-qdrant
    ports:
      - "6333:6333" #RestAPi and Dashboard
      - "6334:6334" #grpc
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: docmind-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: docmind-postgres
    environment:
      POSTGRES_USER: docmind
      POSTGRES_PASSWORD: docmind
      POSTGRES_DB: docmind
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


  langfuse:
    image: langfuse/langfuse:2
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      # Use the service name 'postgres' here
      DATABASE_URL: "postgresql://docmind:docmind@postgres:5432/docmind"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "later"
      SALT: "later"
      TELEMETRY_ENABLED: "false"

volumes:
  qdrant_data:
  redis_data:
  postgres_data:
